#!/bin/bash --

C_LIB=clib2
if (( ${#} > 0 ))
then
    if [[ "${1}" == "clib=newlib" ]]
    then
	C_LIB=newlib
    elif [[ "${1}" != "clib=clib2" ]]
    then
	echo "Could not understand argument ${1}. Only clib=<newlib|clib2[default]> is understood" 1>&2
	exit 1
    fi
fi
INSTALL_PREFIX="$(pwd)/installAmiga_${C_LIB}"

function _error
{
	echo 1>&2 "${1}"
	exit ${2}
}

which ppc-amigaos-gcc 1>/dev/null 2>&1 || _error "Expected ppc-amigaos cross compiler on the path" 10

if [[ ! -d /sdk/ ]]
then
    echo "Error, you do not have a symbolic link named /sdk/ pointing to your ADTOOLS installation SDK" 2>&1
    exit 3
fi

function create_amiga_SDK_package
{
    SDK_DIRS=(
	"local/${C_LIB}/bin"
	"local/${C_LIB}/lib"
	"local/${C_LIB}/share/libxml2/man"
	"local/${C_LIB}/share/libxml2/doc"
	"local/common/include"
    )

    for sdk_dir in "${SDK_DIRS[@]}"
    do
	mkdir -p "${sdk_dir}"
	find "${INSTALL_PREFIX}" -type d -iname "$(basename ${sdk_dir})" -exec cp -r {}/. "${sdk_dir}" \;
    done
    lha a libxslt_1_1_37.lha local/
}

LIB_INFIX=.
if [[ ${C_LIB} == "clib2" ]]
then
    LIB_INFIX=clib2
fi

# TODO: Remove --without-python. Stupid configuration pkg-config issue.
./autogen.sh \
    --prefix="${INSTALL_PREFIX}" \
    --enable-static \
    --disable-shared \
    --without-python \
    --host=ppc-amigaos \
    CFLAGS="-mcrt=${C_LIB}" \
    CXXLAGS="-mcrt=${C_LIB}" \
    CPPFLAGS="-mcrt=${C_LIB}" \
    LDFLAGS="-mcrt=${C_LIB} -athread=native" \
    LIBS="/sdk/../lib/${LIB_INFIX}/libstdc++.a -lpthread"
    
if (( !${?} ))
then
    { make -j$(nproc) && make install ; } || { echo "Error with make" 2>&1 ; exit 1 ; }
    create_amiga_SDK_package
    echo "FINISHED. See libxslt_1_1_37.lha"
else
    echo "Error with configure" 2>&1 ; exit 2
fi
